#!/usr/bin/env python3
"""
Ugly Donuts website image optimizer (one-time / re-runnable offline tool).

What it does (in this order):
1) uploads/*.jpg|jpeg : re-encode in place (max 1600px, q82, progressive, strip metadata)
2) uploads/*.png with REAL transparency : resize+optimize, KEEP png
3) uploads/*.png fully opaque (photo-type) : convert to .jpg (q82) and update
   all references of "/uploads/NAME.png" -> "/uploads/NAME.jpg" in:
     - content/**/*.md
     - root *.html
   (journal/, locations/, _index.json are regenerated by build-index.js)
4) prints a summary. Idempotent: running twice changes nothing meaningful.

Usage: python3 tools/optimize-images.py   (run from repo root)
"""
import glob, io, os, re, sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

MAX_EDGE = 1600
JPEG_Q = 82
CONVERT_MIN_BYTES = 300_000  # only convert opaque PNGs bigger than this

def resize(im):
    w, h = im.size
    if max(w, h) > MAX_EDGE:
        r = MAX_EDGE / max(w, h)
        im = im.resize((max(1, int(w * r)), max(1, int(h * r))), Image.LANCZOS)
    return im

def has_real_alpha(im):
    if im.mode in ('RGBA', 'LA'):
        alpha = im.getchannel('A')
        return alpha.getextrema()[0] < 255
    if im.mode == 'P' and 'transparency' in im.info:
        return True
    return False

def save_jpeg(im, path):
    im.convert('RGB').save(path, 'JPEG', quality=JPEG_Q, optimize=True, progressive=True)

def main():
    before = after = 0
    converted = []  # (old_rel, new_rel)

    for f in sorted(glob.glob('uploads/*')):
        ext = f.rsplit('.', 1)[-1].lower()
        if ext not in ('png', 'jpg', 'jpeg'):
            continue
        size0 = os.path.getsize(f)
        before += size0
        try:
            im = Image.open(f); im.load()
        except Exception as e:
            print(f'  skip (unreadable): {f} ({e})')
            after += size0
            continue
        im = resize(im)

        if ext in ('jpg', 'jpeg'):
            buf = io.BytesIO(); save_jpeg(im, buf)
            if buf.tell() < size0:
                open(f, 'wb').write(buf.getvalue())
        else:  # png
            if has_real_alpha(im):
                buf = io.BytesIO(); im.save(buf, 'PNG', optimize=True)
                if buf.tell() < size0:
                    open(f, 'wb').write(buf.getvalue())
            elif size0 > CONVERT_MIN_BYTES:
                newf = f[:-4] + '.jpg'
                if os.path.exists(newf):
                    # name collision: keep png, just optimize
                    buf = io.BytesIO(); im.save(buf, 'PNG', optimize=True)
                    if buf.tell() < size0:
                        open(f, 'wb').write(buf.getvalue())
                else:
                    save_jpeg(im, newf)
                    os.remove(f)
                    converted.append(('/uploads/' + os.path.basename(f),
                                      '/uploads/' + os.path.basename(newf)))
                    f = newf
            else:
                buf = io.BytesIO(); im.save(buf, 'PNG', optimize=True)
                if buf.tell() < size0:
                    open(f, 'wb').write(buf.getvalue())
        after += os.path.getsize(f)

    # update references for converted files (exact "/uploads/name.png" match)
    if converted:
        srcs = glob.glob('content/**/*.md', recursive=True) + glob.glob('*.html')
        changed = 0
        for s in srcs:
            try:
                c = open(s, encoding='utf-8').read()
            except Exception:
                continue
            c2 = c
            for old, new in converted:
                c2 = c2.replace(old, new)
            if c2 != c:
                open(s, 'w', encoding='utf-8').write(c2)
                changed += 1
        print(f'converted {len(converted)} png->jpg, updated refs in {changed} source files')

    print(f'uploads total: {before/1024/1024:.1f}MB -> {after/1024/1024:.1f}MB')
    # safety: report any source still referencing a missing upload
    missing = set()
    for s in glob.glob('content/**/*.md', recursive=True) + glob.glob('*.html'):
        try:
            c = open(s, encoding='utf-8').read()
        except Exception:
            continue
        for m in re.findall(r'/uploads/[A-Za-z0-9_\-\.\(\)%]+', c):
            p = m.lstrip('/')
            if '%' in p:
                from urllib.parse import unquote
                p = unquote(p)
            if not os.path.exists(p):
                missing.add(m)
    if missing:
        print('WARNING missing refs:', sorted(missing))
    else:
        print('all /uploads references resolve OK')

if __name__ == '__main__':
    main()
